### PR TITLE
[Bugfix #725] Fix CI: move bridge-mode test to integration suite

### LINKED ISSUE #725: Fix main CI: bridge-mode unit test requires built tower-server dist
Main CI started failing after PR #721 merged.\n\nFailing run: https://github.com/cluesmith/codev/actions/runs/25494411894\nFailing job: Unit Tests → Run unit tests with coverage\n\nRoot cause from logs:\n\n```\nFAIL src/agent-farm/__tests__/bridge-mode.test.ts > Bridge Mode\nError: Tower failed to start on port 14900. stderr: Cannot find module '/home/runner/work/codev/codev/packages/codev/dist/agent-farm/servers/tower-server.js'\n```\n\nThe unit-test workflow builds only @cluesmith/codev-core and runs `pnpm copy-skeleton` before `vitest run --coverage`; it does not build `packages/codev/dist`. The newly added `bridge-mode.test.ts` uses the Tower integration helper that spawns `dist/agent-farm/servers/tower-server.js`, so it cannot run in the unit job.\n\nLikely fixes:\n- Move/route `bridge-mode.test.ts` into the Tower integration test suite/job, or\n- Make the test/helper use a source/tsx entrypoint when running under unit tests, or\n- Build packages/codev before unit tests (probably heavier than intended).\n\nAcceptance criteria:\n- Main `Tests` workflow passes.\n- Bridge-mode behavior remains covered in the appropriate CI job.\n- Avoid adding a full codev build to the unit job unless that is the intended tradeoff.

### PR DESCRIPTION
**Pull request by timeleft--**
## Summary
Fixes #725

## Root Cause
`bridge-mode.test.ts` spawns Tower via `dist/agent-farm/servers/tower-server.js`, but the unit-test CI job only builds `@cluesmith/codev-core` — it does not build `packages/codev/dist/`. The test was being picked up by the default vitest config and failing with "Cannot find module".

## Fix
Renamed `bridge-mode.test.ts` → `bridge-mode.e2e.test.ts`, which:
- **Excludes** it from `vitest.config.ts` (unit tests) via the existing `**/*.e2e.test.ts` exclude pattern
- **Includes** it in `vitest.e2e.config.ts` (integration tests) via the existing `src/**/*.e2e.test.ts` include pattern
- Follows the established convention — 13 sibling `.e2e.test.ts` files in the same directory already use this pattern

No config changes needed. Zero-diff rename (file content unchanged).

## Test Plan
- [x] `vitest list` confirms bridge-mode is NOT in unit test list
- [x] `vitest list --config vitest.e2e.config.ts` confirms bridge-mode IS in integration test list
- [x] `vitest run --coverage` passes without bridge-mode (exit 0)
- [x] Existing tests unaffected

### CODE REVIEW

**Comment by timeleft--** [comment]
## Architect Review

Low-risk CI fix. The root cause was that `bridge-mode.test.ts` spawned Tower from `dist/`, but the unit-test workflow does not build `packages/codev/dist`. Renaming the file to `bridge-mode.e2e.test.ts` correctly moves the server-spawning coverage into the existing integration-test suite without changing test behavior or CI config.

Validated PR diff and checks: Unit Tests, Tower Integration Tests, CLI Integration Tests, Package Install Verification, and cross-platform CLI checks are all passing.

Approved to merge.

---
Architect review

**Review by waleedkadous — APPROVED** [review]
Thank you so much for the fix! @otherview just a heads up.
