### ISSUE TITLE
Fix main CI: bridge-mode unit test requires built tower-server dist

### ISSUE THREAD

**Issue by timeleft--** [cluesmith/codev#725]
Main CI started failing after PR #721 merged.\n\nFailing run: https://github.com/cluesmith/codev/actions/runs/25494411894\nFailing job: Unit Tests → Run unit tests with coverage\n\nRoot cause from logs:\n\n```\nFAIL src/agent-farm/__tests__/bridge-mode.test.ts > Bridge Mode\nError: Tower failed to start on port 14900. stderr: Cannot find module '/home/runner/work/codev/codev/packages/codev/dist/agent-farm/servers/tower-server.js'\n```\n\nThe unit-test workflow builds only @cluesmith/codev-core and runs `pnpm copy-skeleton` before `vitest run --coverage`; it does not build `packages/codev/dist`. The newly added `bridge-mode.test.ts` uses the Tower integration helper that spawns `dist/agent-farm/servers/tower-server.js`, so it cannot run in the unit job.\n\nLikely fixes:\n- Move/route `bridge-mode.test.ts` into the Tower integration test suite/job, or\n- Make the test/helper use a source/tsx entrypoint when running under unit tests, or\n- Build packages/codev before unit tests (probably heavier than intended).\n\nAcceptance criteria:\n- Main `Tests` workflow passes.\n- Bridge-mode behavior remains covered in the appropriate CI job.\n- Avoid adding a full codev build to the unit job unless that is the intended tradeoff.

**Comment by timeleft--** [comment]
On it! Working on a fix now.
